/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-02-27 05:08:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"no-js\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <title>Non-Veg Marketing </title>\r\n");
      out.write("        <meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->\r\n");
      out.write("        \r\n");
      out.write("        <!-- Fonts -->\r\n");
      out.write("        <!-- Lato -->\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Lato:400,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css\">\r\n");
      out.write("        \r\n");
      out.write("<!--         <link rel=\"stylesheet\" href=\"css/ionicons.min.css\">\r\n");
      out.write(" -->\r\n");
      out.write("        <!-- CSS -->\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/owl.carousel.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/main.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"css/loginmodal.css\">\r\n");
      out.write("      <!--   <link rel=\"stylesheet\" href=\"css/slider.css\"> -->\r\n");
      out.write("        <!-- Responsive Stylesheet -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("        \r\n");
      out.write("        <style>\r\n");
      out.write("        /* jssor slider bullet navigator skin 01 css */\r\n");
      out.write("        /*\r\n");
      out.write("        .jssorb01 div           (normal)\r\n");
      out.write("        .jssorb01 div:hover     (normal mouseover)\r\n");
      out.write("        .jssorb01 .av           (active)\r\n");
      out.write("        .jssorb01 .av:hover     (active mouseover)\r\n");
      out.write("        .jssorb01 .dn           (mousedown)\r\n");
      out.write("        */\r\n");
      out.write("        .jssorb01 {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("        }\r\n");
      out.write("        .jssorb01 div, .jssorb01 div:hover, .jssorb01 .av {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            /* size of bullet elment */\r\n");
      out.write("            width: 12px;\r\n");
      out.write("            height: 12px;\r\n");
      out.write("            filter: alpha(opacity=70);\r\n");
      out.write("            opacity: .7;\r\n");
      out.write("            /* overflow: hidden; */\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border: #000 1px solid;\r\n");
      out.write("        }\r\n");
      out.write("        .jssorb01 div { background-color: gray; }\r\n");
      out.write("        .jssorb01 div:hover, .jssorb01 .av:hover { background-color: #d3d3d3; }\r\n");
      out.write("        .jssorb01 .av { background-color: #fff; }\r\n");
      out.write("        .jssorb01 .dn, .jssorb01 .dn:hover { background-color: #555555; }\r\n");
      out.write("\r\n");
      out.write("        /* jssor slider arrow navigator skin 13 css */\r\n");
      out.write("        /*\r\n");
      out.write("        .jssora13l                  (normal)\r\n");
      out.write("        .jssora13r                  (normal)\r\n");
      out.write("        .jssora13l:hover            (normal mouseover)\r\n");
      out.write("        .jssora13r:hover            (normal mouseover)\r\n");
      out.write("        .jssora13l.jssora13ldn      (mousedown)\r\n");
      out.write("        .jssora13r.jssora13rdn      (mousedown)\r\n");
      out.write("        .jssora13l.jssora13lds      (disabled)\r\n");
      out.write("        .jssora13r.jssora13rds      (disabled)\r\n");
      out.write("        */\r\n");
      out.write("        .jssora13l, .jssora13r {\r\n");
      out.write("            display: block;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            /* size of arrow element */\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            background: url('images/a13.png') no-repeat;\r\n");
      out.write("           /*  overflow: hidden; */\r\n");
      out.write("        }\r\n");
      out.write("        .jssora13l { background-position: -10px -35px; }\r\n");
      out.write("        .jssora13r { background-position: -70px -35px; }\r\n");
      out.write("        .jssora13l:hover { background-position: -130px -35px; }\r\n");
      out.write("        .jssora13r:hover { background-position: -190px -35px; }\r\n");
      out.write("        .jssora13l.jssora13ldn { background-position: -250px -35px; }\r\n");
      out.write("        .jssora13r.jssora13rdn { background-position: -310px -35px; }\r\n");
      out.write("        .jssora13l.jssora13lds { background-position: -10px -35px; opacity: .3; pointer-events: none; }\r\n");
      out.write("        .jssora13r.jssora13rds { background-position: -70px -35px; opacity: .3; pointer-events: none; }\r\n");
      out.write("    </style>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body id=\"body\">\r\n");
      out.write("\r\n");
      out.write("    \t<div id=\"preloader\">\r\n");
      out.write("    \t\t<div class=\"book\">\r\n");
      out.write("    \t\t  <div class=\"book__page\"></div>\r\n");
      out.write("    \t\t  <div class=\"book__page\"></div>\r\n");
      out.write("    \t\t  <div class=\"book__page\"></div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("\r\n");
      out.write("\t    <!-- \r\n");
      out.write("\t    Header start\r\n");
      out.write("\t    ==================== -->\r\n");
      out.write("\t    <div class=\"navbar-default navbar-fixed-top\" id=\"navigation\">\r\n");
      out.write("\t        <div class=\"container\">\r\n");
      out.write("\t            <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t            <div class=\"navbar-header\">\r\n");
      out.write("\t                <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\">\r\n");
      out.write("\t                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t                    <span class=\"icon-bar\"></span>\r\n");
      out.write("\t                    <span class=\"icon-bar\"></span>\r\n");
      out.write("\t                    <span class=\"icon-bar\"></span>\r\n");
      out.write("\t                </button>\r\n");
      out.write("\t                <label class=\"navbar-brand\" style=\"color:white;\">\r\n");
      out.write("\t                <!-- <img class=\"img-circle\" id=\"img_logo2\" src=\"images/scart.jpg\"> -->\r\n");
      out.write("\t                <i class=\"fa fa-shopping-cart\" aria-hidden=\"true\"></i>&nbsp;NON-VEG MARKET\r\n");
      out.write("                       <!--  <img class=\"logo-1\" src=\"images/logo.png\" alt=\"LOGO\">\r\n");
      out.write("\t                    <img class=\"logo-2\" src=\"images/logo-2.png\" alt=\"LOGO\"> -->\r\n");
      out.write("\t                </label>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\r\n");
      out.write("\t            <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t            <nav class=\"collapse navbar-collapse\" id=\"navbar\">\r\n");
      out.write("\t                <ul class=\"nav navbar-nav navbar-right\" id=\"top-nav\">\r\n");
      out.write("\t                    <li class=\"current\"><a href=\"#body\">Home</a></li>\r\n");
      out.write("\t                    <li><a href=\"#about\">About us</a></li>\r\n");
      out.write("\t                    <li><a href=\"#service\">Services</a></li>\r\n");
      out.write("\t                    <li><a href=\"#contact\">Contact</a></li>\r\n");
      out.write("\t                    <li><a href=\"#\" data-toggle=\"modal\" data-target=\"#login-modal\">Login</a></li>\r\n");
      out.write("\t                </ul>\r\n");
      out.write("\t            </nav><!-- /.navbar-collapse -->\r\n");
      out.write("\t        </div><!-- /.container-fluid -->\r\n");
      out.write("\t    </div>\r\n");
      out.write("\r\n");
      out.write("\t    <section id=\"hero-area\">\r\n");
      out.write("\t    <div class=\"container\">\r\n");
      out.write("\t    <div class=\"row\">   \r\n");
      out.write("\t    <div class=\"col-md-2\"> HELLO</div>\r\n");
      out.write("\t    <div class=col-md-6>      \r\n");
      out.write("    <div id=\"jssor_1\" style=\"position:relative;margin:0 auto;top:0px;left:0px;width:800px;height:300px;\">\r\n");
      out.write("        <!-- Loading Screen -->\r\n");
      out.write("        <div data-u=\"loading\" style=\"position:absolute;top:0px;left:0px;background-color:rgba(0,0,0,0.7);\">\r\n");
      out.write("            <div style=\"filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;\"></div>\r\n");
      out.write("            <div style=\"position:absolute;display:block;background:url('images/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div data-u=\"slides\" style=\"cursor:default;position:relative;top:0px;left:0px;width:800px;height:300px;\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <img data-u=\"image\" src=\"images/001.jpg\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <img data-u=\"image\" src=\"images/002.jpg\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <img data-u=\"image\" src=\"images/003.jpg\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <a data-u=\"any\" href=\"http://www.jssor.com\" style=\"display:none\">Nearby Image Partial Visible Slider</a>\r\n");
      out.write("            <div>\r\n");
      out.write("                <img data-u=\"image\" src=\"images/004.jpg\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <img data-u=\"image\" src=\"images/005.jpg\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <img data-u=\"image\" src=\"images/006.jpg\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <img data-u=\"image\" src=\"images/007.jpg\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <img data-u=\"image\" src=\"images/008.jpg\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- <div>\r\n");
      out.write("                <img data-u=\"image\" src=\"images/009.jpg\" />\r\n");
      out.write("            </div> -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Bullet Navigator -->\r\n");
      out.write("        <div data-u=\"navigator\" class=\"jssorb01\" style=\"bottom:16px;right:16px;\" data-autocenter=\"1\">\r\n");
      out.write("            <div data-u=\"prototype\" style=\"width:12px;height:12px;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Arrow Navigator -->\r\n");
      out.write("        <span data-u=\"arrowleft\" class=\"jssora13l\" style=\"top:0px;left:30px;width:40px;height:50px;\" data-autocenter=\"2\"></span>\r\n");
      out.write("        <span data-u=\"arrowright\" class=\"jssora13r\" style=\"top:0px;right:30px;width:40px;height:50px;\" data-autocenter=\"2\"></span>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div class=\"col-md-2\"></div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t    \r\n");
      out.write("\t        <div class=\"container\">\r\n");
      out.write("\t            <div class=\"row\">\r\n");
      out.write("\t                <div class=\"col-md-6\">\r\n");
      out.write("\t                    <div class=\"block\">\r\n");
      out.write("\t                        <h1 class=\"wow fadeInDown\">ORDER YOUR NON-VEG ITESM</h1>\r\n");
      out.write("\t                        <p class=\"wow fadeInDown\" data-wow-delay=\"0.3s\">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna</p>\r\n");
      out.write("\t                        <div class=\"wow fadeInDown\" data-wow-delay=\"0.3s\">\r\n");
      out.write("\t                        \t<a class=\"btn btn-default btn-home\" href=\"#about\" role=\"button\">BOOK ORDER</a>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"col-md-6 wow zoomIn\">\r\n");
      out.write("\t                    <div class=\"block\">\r\n");
      out.write("\t                        <div class=\"counter text-center\">\r\n");
      out.write("\t                            <ul id=\"countdown_dashboard\">\r\n");
      out.write("\t                                <li>\r\n");
      out.write("\t                                    <div class=\"dash days_dash\">\r\n");
      out.write("\t                                        <div class=\"digit\">0</div>\r\n");
      out.write("\t                                        <div class=\"digit\">0</div>\r\n");
      out.write("\t                                        <div class=\"digit\">0</div>\r\n");
      out.write("\t                                        <span class=\"dash_title\">Days</span>\r\n");
      out.write("\t                                    </div>\r\n");
      out.write("\t                                </li>\r\n");
      out.write("\t                                <li>\r\n");
      out.write("\t                                    <div class=\"dash hours_dash\">\r\n");
      out.write("\t                                        <div class=\"digit\">0</div>\r\n");
      out.write("\t                                        <div class=\"digit\">0</div>\r\n");
      out.write("\t                                        <span class=\"dash_title\">Hours</span>\r\n");
      out.write("\t                                    </div>\r\n");
      out.write("\t                                </li>\r\n");
      out.write("\t                                <li>\r\n");
      out.write("\t                                    <div class=\"dash minutes_dash\">\r\n");
      out.write("\t                                        <div class=\"digit\">0</div>\r\n");
      out.write("\t                                        <div class=\"digit\">0</div>\r\n");
      out.write("\t                                        <span class=\"dash_title\">Minutes</span>\r\n");
      out.write("\t                                    </div>\r\n");
      out.write("\t                                </li>\r\n");
      out.write("\t                                <li>\r\n");
      out.write("\t                                    <div class=\"dash seconds_dash\">\r\n");
      out.write("\t                                        <div class=\"digit\">0</div>\r\n");
      out.write("\t                                        <div class=\"digit\">0</div>\r\n");
      out.write("\t                                        <span class=\"dash_title\">Seconds</span>\r\n");
      out.write("\t                                    </div>\r\n");
      out.write("\t                                </li>\r\n");
      out.write("\t                            </ul>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div><!-- .row close -->\r\n");
      out.write("\t        </div><!-- .container close -->\r\n");
      out.write("\t    </section><!-- header close -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Login Modal  -->\r\n");
      out.write("<!-- BEGIN # MODAL LOGIN -->\r\n");
      out.write("<div class=\"modal fade\" id=\"login-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\" style=\"display: none;\">\r\n");
      out.write("    \t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<img class=\"img-circle\" id=\"img_logo\" src=\"images/loginlogo.png\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"ion-close\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Begin # DIV Form -->\r\n");
      out.write("                <div id=\"div-forms\">\r\n");
      out.write("                \r\n");
      out.write("                    <!-- Begin # Login Form -->\r\n");
      out.write("                    <form id=\"login-form\">\r\n");
      out.write("\t\t                <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t    \t\t<div id=\"div-login-msg\">\r\n");
      out.write("                                <div id=\"icon-login-msg\" class=\"ion-chevron-right\"></div>\r\n");
      out.write("                                <span id=\"text-login-msg\">Type your username and password.</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\t\t\t\t    \t\t<input id=\"login_username\" class=\"form-control\" type=\"text\" placeholder=\"Username (type ERROR for error effect)\" required>\r\n");
      out.write("\t\t\t\t    \t\t<input id=\"login_password\" class=\"form-control\" type=\"password\" placeholder=\"Password\" required>\r\n");
      out.write("                            <div class=\"checkbox\">\r\n");
      out.write("                                <label>\r\n");
      out.write("                                    <input type=\"checkbox\"> Remember me\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("        \t\t    \t</div>\r\n");
      out.write("\t\t\t\t        <div class=\"modal-footer\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary btn-lg btn-block\">Login</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("\t\t\t\t    \t    <!-- <div>\r\n");
      out.write("                                <button id=\"login_lost_btn\" type=\"button\" class=\"btn btn-link\">Lost Password?</button>\r\n");
      out.write("                                <button id=\"login_register_btn\" type=\"button\" class=\"btn btn-link\">Register</button>\r\n");
      out.write("                            </div> -->\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <!-- End # Login Form -->\r\n");
      out.write("</div></div></div></div>\r\n");
      out.write("<!--END MODAL LOGIN  -->\r\n");
      out.write("        <!-- \r\n");
      out.write("        About start\r\n");
      out.write("        ==================== -->\r\n");
      out.write("        <section id=\"about\" class=\"section\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-7 col-sm-12 wow fadeInLeft\">\r\n");
      out.write("                    \t<div class=\"sub-heading\">\r\n");
      out.write("                    \t\t<h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam ipsa recusandae consequatur veniam, reiciendis odit quia eaque vel eius a.</h3>\r\n");
      out.write("                    \t</div>\r\n");
      out.write("                        <div class=\"block\">\r\n");
      out.write("                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ulla-mco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in</p>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque, aspernatur.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-5 col-sm-12 wow fadeInLeft\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                        <div class=\"about-slider\">\r\n");
      out.write("                        \t<div class=\"init-slider\">\r\n");
      out.write("                        \t\t<div class=\"about-item\">\r\n");
      out.write("                        \t\t\t<img src=\"images/about/1.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                        \t\t</div>\r\n");
      out.write("                        \t\t<div class=\"about-item\">\r\n");
      out.write("                        \t\t\t<img src=\"images/about/2.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                        \t\t</div>\r\n");
      out.write("                        \t\t<div class=\"about-item\">\r\n");
      out.write("                        \t\t\t<img src=\"images/about/3.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                        \t\t</div>\r\n");
      out.write("                        \t</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section><!-- #about close -->\r\n");
      out.write("        <!-- \r\n");
      out.write("        About start\r\n");
      out.write("        ==================== -->\r\n");
      out.write("\r\n");
      out.write("        <!-- \r\n");
      out.write("        Service start\r\n");
      out.write("        ==================== -->\r\n");
      out.write("        <section id=\"service\" class=\"section\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"heading wow fadeInUp\">\r\n");
      out.write("                        <h2>Our service</h2>\r\n");
      out.write("                        <p>We are Providing the Best Quality Of non-veg item's in Bhubaneswar Area..<br> Here you are going to get the Fully Fresh Item as Market Ex:-</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-6 col-md-3 wow fadeInLeft\">\r\n");
      out.write("                        <div class=\"service\">\r\n");
      out.write("                            <div class=\"icon-box\">\r\n");
      out.write("                            \t<span class=\"icon\">\r\n");
      out.write("                                    <i class=\"ion-android-desktop\"></i>   \r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"caption\">\r\n");
      out.write("                                <h3>Fresh Chicken</h3>\r\n");
      out.write("                                <p>XXXXXXXXXXXXXXXXXXXX</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-6 col-md-3 wow fadeInLeft\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                        <div class=\"service\">\r\n");
      out.write("                            <div class=\"icon-box\">\r\n");
      out.write("                            \t<span class=\"icon\">\r\n");
      out.write("                                    <i class=\"ion-speedometer\"></i>   \r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"caption\">\r\n");
      out.write("                            \t<h3>Fresh Fish</h3>\r\n");
      out.write("                                <p>XXXXXXXXXXXXXXX</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-6 col-md-3 wow fadeInLeft\" data-wow-delay=\"0.6s\">\r\n");
      out.write("                        <div class=\"service\">\r\n");
      out.write("                            <div class=\"icon-box\">\r\n");
      out.write("                            \t<span class=\"icon\">\r\n");
      out.write("                                    <i class=\"ion-ios-infinite-outline\"></i>   \r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"caption\">\r\n");
      out.write("                                <h3>Egg's</h3>\r\n");
      out.write("                                <p>XXXXXXXXXXXXXXXXX</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-6 col-md-3 wow fadeInLeft\" data-wow-delay=\"0.9s\">\r\n");
      out.write("                        <div class=\"service\">\r\n");
      out.write("                            <div class=\"icon-box\">\r\n");
      out.write("                            \t<span class=\"icon\">\r\n");
      out.write("                                    <i class=\"ion-ios-cloud-outline\"></i>   \r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"caption\">\r\n");
      out.write("                                <h3>Fresh Mutton</h3>\r\n");
      out.write("                                <p>XXXXXXXXXXXXXXXXXXXX</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div><!-- .container close -->\r\n");
      out.write("        </section><!-- #service close -->\r\n");
      out.write("\r\n");
      out.write("      <!--  <section id=\"call-to-action\" class=\"section\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12 wow text-center\">\r\n");
      out.write("                        <div class=\"block\">\r\n");
      out.write("                            <h2>Lorem ipsum dolor sit amet, consectetur adipisicing</h2>\r\n");
      out.write("                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod</p>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"Enter Your Email Address\">\r\n");
      out.write("                                <button class=\"btn btn-default btn-submit\" type=\"submit\">Get Notified</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section><!-- #call-to-action close -->\r\n");
      out.write("\t\r\n");
      out.write("        <!-- \r\n");
      out.write("        Contact start\r\n");
      out.write("        ==================== -->\r\n");
      out.write("        <section id=\"contact\" class=\"section\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xs-12 col-sm-12 col-md-12\">\r\n");
      out.write("                        <div class=\"block\">\r\n");
      out.write("                            <div class=\"heading wow fadeInUp\">\r\n");
      out.write("                                <h2>Get In Touch</h2>\r\n");
      out.write("                                <p>XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xs-12 col-sm-12 col-md-5 wow fadeInUp\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"block text-left\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"sub-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>Contact Address</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>We are Located at the Heart Of the Bhubaneswar City,We are pleased to Help You.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<address class=\"address\">\r\n");
      out.write("                                <hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Saheed Nagar,<br> Bhubaneswar,<br> Odisha</p>\r\n");
      out.write("                                <hr>\r\n");
      out.write("                                <p><strong>E-mail:</strong>&nbsp;nonvegmarkets@gmail.com<br>\r\n");
      out.write("                                <strong>Mobile:</strong>&nbsp;+91 9861787560,+91 9853585363,+91 9583702116</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("                                \r\n");
      out.write("\t\t\t\t\t\t\t</address>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-xs-12 col-sm-12 col-md-5 col-md-offset-1 wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                    \t<div class=\"form-group\">\r\n");
      out.write("                    \t    <form action=\"#\" method=\"post\" id=\"contact-form\">\r\n");
      out.write("                    \t        <div class=\"input-field\">\r\n");
      out.write("                    \t            <input type=\"text\" class=\"form-control\" placeholder=\"Your Name\" name=\"name\">\r\n");
      out.write("                    \t        </div>\r\n");
      out.write("                    \t        <div class=\"input-field\">\r\n");
      out.write("                    \t            <input type=\"email\" class=\"form-control\" placeholder=\"Email Address\" name=\"email\">\r\n");
      out.write("                    \t        </div>\r\n");
      out.write("                    \t        <div class=\"input-field\">\r\n");
      out.write("                    \t            <textarea class=\"form-control\" placeholder=\"Your Message\" rows=\"3\" name=\"message\"></textarea>\r\n");
      out.write("                    \t        </div>\r\n");
      out.write("                    \t        <button class=\"btn btn-send\" type=\"submit\">Send me</button>\r\n");
      out.write("                    \t    </form>\r\n");
      out.write("\r\n");
      out.write("                    \t    <div id=\"success\">\r\n");
      out.write("                    \t        <p>Your Message was sent successfully</p>\r\n");
      out.write("                    \t    </div>\r\n");
      out.write("                    \t    <div id=\"error\">\r\n");
      out.write("                    \t        <p>Your Message was not sent successfully</p>\r\n");
      out.write("                    \t    </div>\r\n");
      out.write("                    \t</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section clas=\"wow fadeInUp\">\r\n");
      out.write("        \t<div class=\"map-wrapper\">\r\n");
      out.write("        \t</div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <footer>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                        <div class=\"block\">\r\n");
      out.write("                            <p>Copyright &copy; <a href=\"http://www.nonvegmarkets.com\">NonvegMarkets</a>| All right reserved.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Js -->\r\n");
      out.write("        \r\n");
      out.write("        <script src=\"js/vendor/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("        <script src=\"js/vendor/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("        <script src=\"https://maps.googleapis.com/maps/api/js?sensor=false\"></script>\r\n");
      out.write("        <script src=\"js/jquery.lwtCountdown-1.0.js\"></script>\r\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("        <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("        <script src=\"js/jquery.validate.min.js\"></script>\r\n");
      out.write("        <script src=\"js/jquery.form.js\"></script>\r\n");
      out.write("        <script src=\"js/jquery.nav.js\"></script>\r\n");
      out.write("        <script src=\"js/jquery.sticky.js\"></script>\r\n");
      out.write("        <script src=\"js/plugins.js\"></script>\r\n");
      out.write("        <script src=\"js/wow.min.js\"></script>\r\n");
      out.write("        <script src=\"js/main.js\"></script>\r\n");
      out.write("        <script src=\"js/slider/jssor.slider-22.2.8.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("        <script src=\"js/loginmodal.js\"></script>\r\n");
      out.write("       \r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("        jssor_1_slider_init = function() {\r\n");
      out.write("\r\n");
      out.write("            var jssor_1_options = {\r\n");
      out.write("              $AutoPlay: true,\r\n");
      out.write("              $SlideWidth: 600,\r\n");
      out.write("              $Cols: 2,\r\n");
      out.write("              $Align: 100,\r\n");
      out.write("              $ArrowNavigatorOptions: {\r\n");
      out.write("                $Class: $JssorArrowNavigator$\r\n");
      out.write("              },\r\n");
      out.write("              $BulletNavigatorOptions: {\r\n");
      out.write("                $Class: $JssorBulletNavigator$\r\n");
      out.write("              }\r\n");
      out.write("            };\r\n");
      out.write("\r\n");
      out.write("            var jssor_1_slider = new $JssorSlider$(\"jssor_1\", jssor_1_options);\r\n");
      out.write("\r\n");
      out.write("            /*responsive code begin*/\r\n");
      out.write("            /*you can remove responsive code if you don't want the slider scales while window resizing*/\r\n");
      out.write("            function ScaleSlider() {\r\n");
      out.write("                var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;\r\n");
      out.write("                if (refSize) {\r\n");
      out.write("                    refSize = Math.min(refSize, 800);\r\n");
      out.write("                    jssor_1_slider.$ScaleWidth(refSize);\r\n");
      out.write("                }\r\n");
      out.write("                else {\r\n");
      out.write("                    window.setTimeout(ScaleSlider, 30);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            ScaleSlider();\r\n");
      out.write("            $Jssor$.$AddEvent(window, \"load\", ScaleSlider);\r\n");
      out.write("            $Jssor$.$AddEvent(window, \"resize\", ScaleSlider);\r\n");
      out.write("            $Jssor$.$AddEvent(window, \"orientationchange\", ScaleSlider);\r\n");
      out.write("            /*responsive code end*/\r\n");
      out.write("        };\r\n");
      out.write("    </script>\r\n");
      out.write("          <script type=\"text/javascript\">jssor_1_slider_init();</script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
